### PR TITLE
Bug Image fix mobile view 152

### LINKED ISSUE #152: [BUG] Image not showing properly in mobile view
### Problem subject

Other: Image orientation issue

### Description

Top of the image is cut off in mobile view For the following pages
Creators
Developers
Patrons
Screenshot:
image

### Expected behavior/contents

Full Image should be visible

### Actual behavior/contents

Image Cut off from top

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AbhinavMV**
#### Description of the change

closes #152 
#### Screenshots
image

#### Checklist

**I agree to the following :-**

*   Added description of the change
*   I've read the [contributing guidelines](https://github.com/web3community/devprotocol.xyz/blob/main/CONTRIBUTING.md)
*   Search previous suggestions before making a new PR, as yours may be a duplicate.
*   I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**): 

<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/154"></a>

### CODE REVIEW

**Review by vinzvinci — APPROVED** [review]
LGTM 👍

**Review by shuklaritvik06 — APPROVED** [review]
Thank you so much for your contributions!! LGTM

**Review by krishguptadev — COMMENTED** [review]
LGTM!

**Review by Panquesito7 — COMMENTED** [review]
LGTM! 🚀

**Pull request merged**
