### PR TITLE
Improved slider section

### LINKED ISSUE #63: [FEATURE] Improve the slider section
### Detailed description

Krish is suggesting improve the slider section 

### Context

image
 +
reduce the white space in mobile and tablet view
image
+
try to adopt the alignment of logo
image

### Possible implementation

Figma link: https://www.figma.com/file/rmCKKIsjSWCH0q6lObDQC8/Dev-Protocol-design?node-id=0%3A1

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ZaidKhan2002**
#### Description of the change

Improved slider section but adjusting image according to design and reduced white spacing in mobile size.
Closes #63 

#### Screenshots

Screenshot 2021-11-11 at 12 15 49 PM

Screenshot 2021-11-11 at 12 16 07 PM

#### Checklist

- [x] Added description of the change
- [x] I've read the [contributing guidelines](https://github.com/web3community/devprotocol.xyz/blob/main/CONTRIBUTING.md)
- [x] Search previous suggestions before making a new PR, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**): 

<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/130"></a>

### CODE REVIEW

**Review by krishguptadev — APPROVED** [review]

**Review by vinzvinci — APPROVED** [review]

**Review by Panquesito7 — COMMENTED** [review]
What happened with the `package-lock.json` file here? 👀

**Comment by krishguptadev** [comment]
> What happened with the `package-lock.json` file here? 👀
> 

Wait a minute, don't we use yarn?

**Comment by Panquesito7** [comment]
> > What happened with the `package-lock.json` file here? 👀
> 
> Wait a minute, don't we use yarn?

Yeah. Going to fix it right away. 🙂

**Comment by krishguptadev** [comment]
> > > What happened with the `package-lock.json` file here? 👀
> > 
> > Wait a minute, don't we use yarn?
> 
> Yeah. Going to fix it right away. 🙂
> 

You working on it or shall I make a PR?

**Comment by Panquesito7** [comment]
> > > > What happened with the `package-lock.json` file here? 👀
> > > 
> > > 
> > > Wait a minute, don't we use yarn?
> > 
> > 
> > Yeah. Going to fix it right away. 🙂
> 
> You working on it or shall I make a PR?

Made it.

**Comment by krishguptadev** [comment]
> > > > > What happened with the `package-lock.json` file here? 👀
> > > > 
> > > > 
> > > > Wait a minute, don't we use yarn?
> > > 
> > > 
> > > Yeah. Going to fix it right away. 🙂
> > 
> > 
> > You working on it or shall I make a PR?
> 
> Made it.

Cool, just waiting a second approval...

**Pull request merged**
