### PR TITLE
Implement new section (L2), finalize links, use grid-gap instead of padding for each component

### PR DESCRIPTION
**Pull request by vinzvinci**
#### Description of the change

You can see the changes here http://devprotocol.xyz/

#### Screenshots

N/A

#### Checklist

- [ ] Added description of the change
- [ ] I've read the [contributing guidelines](https://github.com/web3community/devprotocol.xyz/blob/main/CONTRIBUTING.md)
- [ ] Search previous suggestions before making a new PR, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**): 

<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/100"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Awesome! Thanks, @vinzvinci, and @aggre! 🚀

**Review by shuklaritvik06 — APPROVED** [review]
LGTM ✨

**Review by KukretiShubham — APPROVED** [review]
LGTM 🚀

**Review by mkubdev — APPROVED** [review]
Nice work 🚀

**Review by krishguptadev — COMMENTED** [review]
LGTM!

**Pull request merged**
