### PR TITLE
fix(styles): Added responsiveness

### PR DESCRIPTION
**Pull request by boidushya**
#### Checklist

- [x] Added description of the change
- [x] I've read the [contributing guidelines](https://github.com/web3community/devprotocol.xyz/blob/master/CONTRIBUTING.md)
- [x] Search previous suggestions before making a new PR, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**): 

Issue #51 
Navbar still needs work, but general responsiveness is addressed

### CODE REVIEW

**Comment by vinzvinci** [comment]
> okay! I just wanted to make sure if its fine to hide the join button, thanks! ill look into it

Cool cool

**Comment by krishguptadev** [comment]
> okay! I just wanted to make sure if its fine to hide the join button, thanks! ill look into it

Don't hide the join button, just move the 3 nav links to a ham

**Comment by vinzvinci** [comment]
> Looks good, but can u add hamburger in navbar for these 3? image
> 
> U can hide that **Join** button image

Let's do this request first, we can change this if needed soon.

**Comment by boidushya** [comment]
i could add the join button below/above the options in hamburger menu if needed...

**Comment by vinzvinci** [comment]
> @vinzvinci @krishguptadev check the recent commit

Sorry for less details. Can u do this instead on the right side?
image

demo link: https://devprotocol.xyz/

**Comment by krishguptadev** [comment]
> > @vinzvinci @krishguptadev check the recent commit
> 
> Sorry for less details. Can u do this instead on the right side? image
> 
> demo link: https://devprotocol.xyz/
> 
> I think that's much better

@boidushya Basically make it full screen

**Comment by boidushya** [comment]
> > > @vinzvinci @krishguptadev check the recent commit
> > 
> > 
> > Sorry for less details. Can u do this instead on the right side? image
> > demo link: https://devprotocol.xyz/
> > I think that's much better
> 
> @boidushya Basically make it full screen

yup one sec

**Comment by boidushya** [comment]
Its okay if i keep a white background right?

**Comment by vinzvinci** [comment]
> Its okay if i keep a white background right?

yes

**Comment by boidushya** [comment]
@vinzvinci @krishguptadev could you check the commit?

**Comment by boidushya** [comment]
> LGTM!

Thanks! Could you also add a `hacktoberfest-accepted` tag once its merged?

**Comment by boidushya** [comment]
> > > LGTM!
> > 
> > 
> > Thanks! Could you also add a `hacktoberfest-accepted` tag once its merged?
> 
> @boidushya Our repo has the hacktoberfest label, this means we do not need to add the `hacktoberfest-accepted` label to PRs, It will automatically count once we merge it. But yet I'll add it to resolve any future confusions.

Thanks :)

**Pull request merged**
