### PR TITLE
[REFACTOR]: FAQ translation management made easier

### PR DESCRIPTION
**Pull request by Simperfy**
#### Description of the change
- Added dropdown for language selection in FAQ
- Moved FAQ translation to `CSV` file for easier management.
   - Sample csv file can be found [here](https://docs.google.com/spreadsheets/d/19jggfoN6dT4W9zIJC6Tmo73XaeFOqbsgq_Y7oZPlvLQ/edit?usp=sharing)
  - FAQ can now be easily extended to support other languages *(if needed in the future)*.
  - CSV file must be in UTF-8 encoding in order to display the japanese characters correctly.
  - By separating the language file the cognitive complexity in `Faq.vue` was significantly reduced.
  - This will also enable the possibility of auto-translation using google sheets. *(if necessary)*
- Added `snowpack-plugin-dsv` to parse .csv files

**Note: If you open the file using microsoft excel don't forget to change encoding to UTF-8**

#### Screenshots
Sample CSV *(test language not included in final file changes)*.

a

Here's the dropdown, adding additional languages in `CSV` file automatically creates a corresponding list item in the dropdown. 

b

It automatically updates the translation without touching any javascript code.

d

#### Checklist

**I agree to the following :-**

*   Added description of the change
*   I've read the [contributing guidelines](https://github.com/web3community/devprotocol.xyz/blob/main/CONTRIBUTING.md)
*   Search previous suggestions before making a new PR, as yours may be a duplicate.
*   I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**): 

<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/165"></a>

### CODE REVIEW

**Comment by Panquesito7** [comment]
Awesome work, thanks! 🚀 We were also discussing using [Weblate](https://weblate.org/) for translations in our project. This is also a good way, though! 😄 Thank you.

**Review by vinzvinci — APPROVED** [review]
Awesome! LGTM 👍

**Review by vinzvinci — APPROVED** [review]
Awesome! LGTM 👍

**Review by krishguptadev — APPROVED** [review]

**Review by Panquesito7 — COMMENTED** [review]
LGTM! 🚀

**Pull request merged**
