### PR TITLE
fix: Discord invitation link

### PR DESCRIPTION
**Pull request by Panquesito7**
#### Description of the change

- Fix the Discord invitation link.

#### Checklist

- [x] Added description of the change
- [x] I've read the [contributing guidelines](https://github.com/web3community/devprotocol.xyz/blob/main/CONTRIBUTING.md)
- [x] Search previous suggestions before making a new PR, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**): 

<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/101"></a>

### CODE REVIEW

**Review by krishguptadev — COMMENTED** [review]
This looks good but can't we have a short URL for the invite.

**Comment by Panquesito7** [comment]
> This looks good but can't we have a short URL for the invite.

Like a domain? Something like `discord.devprotocol.xyz`?

**Comment by krishguptadev** [comment]
> > This looks good but can't we have a short URL for the invite.
> 
> Like a domain? Something like `discord.devprotocol.xyz`?

Yep! Like I have krish.ninja/github

**Comment by Panquesito7** [comment]
> > > This looks good but can't we have a short URL for the invite.
> > 
> > 
> > Like a domain? Something like `discord.devprotocol.xyz`?
> 
> Yep! Like I have krish.ninja/github

@vinzvinci, @aggre.

**Comment by vinzvinci** [comment]
Yeah cool, will notify aggre in discord

**Pull request merged**
