### PR TITLE
Build the base website.

### PR DESCRIPTION
**Pull request by krishguptadev**
Since we the issue was to be meant to be done by more than one person. I've added the desktop version of the site. It doesn't need much but a little bit of toggling with fonts on smaller screen sizes. That could be done by more contributors. I've also added a few comment where automation is required and we need to discuss.

### CODE REVIEW

**Comment by vinzvinci** [comment]
It will be cool if u share some demo or screenshots

**Comment by krishguptadev** [comment]
image
image
image
image
image

**Review by mkubdev — APPROVED** [review]
Awesome! Thanks for your contribution @krishguptadev 👏
Astro looks like Alpine! Can't wait to test this stack. LGTM 🎃🚀

**Comment by krishguptadev** [comment]
btw @mkubdev With astro you can use React, Preact, Vue or Svelte together with it (you can choose multiple too). IE I wrote the basic stuff in plain html, when we make the slider we could use vue or svelte which would also be compiled to static html, check this out once: https://astro.build/

**Review by vinzvinci — APPROVED** [review]
Thanks for: 
- Putting comments
- Organized files
- Clean codes

There are some small changes needed but since this is still in implementing phase, we can approve this PR and enhance it next PR.

I like to know what the other team thoughts here

> Thank you for the big PR 🎉

**Comment by krishguptadev** [comment]
> Thanks for:
> 
> * Putting comments
> * Organized files
> * Clean codes
> 
> There are some small changes needed but since this is still in implementing phase, we can approve this PR and enhance it next PR.
> 
> I like to know what the other team thoughts here
> 
> > Thank you for the big PR 🎉

I would like to make a few issues for features apart from what this pr introduced! I would be making them once this is merged... Thanks for the opportunity for letting me to contribute to the web3community!

**Comment by mkubdev** [comment]
> btw @mkubdev With astro you can use React, Preact, Vue or Svelte together with it (you can choose multiple too). IE I wrote the basic stuff in plain html, when we make the slider we could use vue or svelte which would also be compiled to static html, check this out once: https://astro.build/

So cool. Thanks for sharing it ! 🌞 btw i love preact !!

**Review by shuklaritvik06 — APPROVED** [review]
Awesome krish 🎉

**Pull request merged**
