### PR TITLE
A few style changes

### PR DESCRIPTION
**Pull request by SyedFasiuddin**
- made the nav bar transluecent
- added a bottom border to navbar
- fixed the spacing on the join button in navbar
- in footer added space between the twitter and medium links
- made the test to justify in many places
- resolved the conflicts that occured

- [x] Added description of the change
- [x] I've read the [contributing guidelines](https://github.com/web3community/devprotocol.xyz/blob/master/CONTRIBUTING.md)
- [x] Search previous suggestions before making a new PR, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by aggre** [comment]
I want to tweak the text in the slider, so I'll hotfix it in dev-protocol/devprotocol.xyz. Once this PR is merged, I'll pull it and create another PR to reflect the hotfix text.

**Comment by SyedFasiuddin** [comment]
> 
> 
> I have suggestion, can u remove that horizontal line in navbar?

Just the border ?

**Comment by SyedFasiuddin** [comment]
so you want me to make the navbar normal? like it was before

**Comment by vinzvinci** [comment]
Krish is also referring to code styling

**Comment by SyedFasiuddin** [comment]
> 
> 
> Krish is also referring to code styling

what code style do you want me to change, if you can specify how you guys do this then I'll be able to follow those rules

**Pull request closed without merging**
