### PR TITLE
[UPDATE]: Improved the color combination of community partners page in light mode

### PR DESCRIPTION
**Pull request by Simperfy**
The background color of cards in community page when using light mode is highly distracting.

#### Description of the change
- Changed the background color of community partners background color to white when in light mode.
- Added a touch of gray in background color of community partners when in dark mode. 
- Added slight highlight to "visit site" button.

#### Screenshots
Current design *(light mode)*:
image

Proposed changes *(light mode)*:
image

<hr>

Current design *(dark mode)*:
image

Proposed changes *(dark mode)*:
image

#### Checklist

**I agree to the following :-**

*   Added description of the change
*   I've read the [contributing guidelines](https://github.com/web3community/devprotocol.xyz/blob/main/CONTRIBUTING.md)
*   Search previous suggestions before making a new PR, as yours may be a duplicate.
*   I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**): 

<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/172"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Awesome! 🚀

**Review by shuklaritvik06 — APPROVED** [review]
Looks good, let's wait for vinz final approval

**Review by vinzvinci — APPROVED** [review]
LGTM 👍

**Review by krishguptadev — CHANGES_REQUESTED** [review]
Can't we use our darkPrimary color?

**Comment by Simperfy** [comment]
> Can't we use our darkPrimary color?

I've removed that since it causes the cards to have a distracting highlight, and also it's suppose to be a light theme but majority of color present is dark.

**Review by krishguptadev — APPROVED** [review]

**Comment by shuklaritvik06** [comment]
As all reviewers approved so i am merging this PR, Thank you @Simperfy  for the contribution ✨

**Pull request merged**
