### PR TITLE
fix: image resolution and sizing

### PR DESCRIPTION
**Pull request by gptkrsh**
fixes the issue of the images going into weird sizes

### CODE REVIEW

**Comment by Panquesito7** [comment]
> image

For me, some of the images still look stretched which makes it look bad. Would you want to look at that and fix it? 🙂

**Comment by krishguptadev** [comment]
> > image
> 
> For me, some of the images still look stretched which makes it look bad. Would you want to look at that and fix it? 🙂

Only the Sios image is stretched that too coz of the image being stretched: https://github.com/web3community/devprotocol.xyz/blob/main/public/assets/sios.png

Not a issue with the code. afaik

**Comment by Panquesito7** [comment]
> > > image
> > 
> > 
> > For me, some of the images still look stretched which makes it look bad. Would you want to look at that and fix it? 🙂
> 
> Only the Sios image is stretched that too coz of the image being stretched: https://github.com/web3community/devprotocol.xyz/blob/main/public/assets/sios.png
> 
> Not a issue with the code. afaik

Nope, it's not an issue with the code, but if this PR is about fixing the resolution and sizing, the images should be fixed then, I think.

**Comment by Panquesito7** [comment]
> > > > > image
> > > > 
> > > > 
> > > > For me, some of the images still look stretched which makes it look bad. Would you want to look at that and fix it? 🙂
> > > 
> > > 
> > > Only the Sios image is stretched that too coz of the image being stretched: https://github.com/web3community/devprotocol.xyz/blob/main/public/assets/sios.png
> > > Not a issue with the code. afaik
> > 
> > 
> > Nope, it's not an issue with the code, but if this PR is about fixing the resolution and sizing, the images should be fixed then, I think.
> 
> @vinzvinci Do you have the correct file for Sios. I think that's the only one that's wrong

The `Microsoft for Startups` also looks kind of stretched, IMO.

**Comment by krishguptadev** [comment]
image

**Pull request merged**
